import Foundation

struct LessonDetails {
    let overview: String
    let keyPoints: [String]
    let practicalUse: String
}

enum LessonDetailsCatalog {
    static let values = LessonDetails(overview: "Values give names to data. A constant declared with let cannot be reassigned, while a variable declared with var can change. Every value has a type, either written explicitly or inferred by Swift.", keyPoints: ["Prefer let until mutation is required.", "Common types include String, Int, Double, and Bool.", "Strong typing catches incompatible assignments at compile time."], practicalUse: "SwiftUI state, configuration, user input, and model properties all begin as constants or variables.")
    static let controlFlow = LessonDetails(overview: "Control flow decides which code runs and how often. Conditions use if, multi-case decisions use switch, and loops process sequences of values.", keyPoints: ["if handles Boolean conditions.", "switch should exhaustively cover every possible case.", "A for-in loop performs regular Swift work; SwiftUI ForEach creates views."], practicalUse: "Use control flow for validation, permissions, loading states, filtering, and preparing data for views.")
    static let functions = LessonDetails(overview: "Functions package related work behind a reusable name. Parameters supply input, return values provide output, and function types allow behavior to be passed around.", keyPoints: ["Parameter labels make calls readable.", "Use -> to declare a return type.", "Keep functions focused on one responsibility."], practicalUse: "Functions reduce repetition and make business logic independently testable.")
    static let optionals = LessonDetails(overview: "An optional represents either a wrapped value or nil. It forces missing data to be handled deliberately instead of allowing unsafe assumptions.", keyPoints: ["String? may contain a String or nil.", "Use if let for conditional work and guard let for early exits.", "Avoid force unwrapping with ! unless validity is guaranteed."], practicalUse: "Optionals appear in network responses, searches, user input, navigation selection, and failed conversions.")
    static let collections = LessonDetails(overview: "Collections store groups of values. Arrays preserve order, sets enforce uniqueness, and dictionaries associate unique keys with values.", keyPoints: ["Array access is index-based.", "Set membership checks are fast.", "Dictionary lookup returns an optional because a key may be absent."], practicalUse: "Most app screens render collections received from local storage or APIs.")
    static let semantics = LessonDetails(overview: "Structs are value types, so assigning them creates independent values. Classes are reference types, so multiple variables can point to the same instance and identity.", keyPoints: ["Swift models commonly use structs.", "Classes support identity, inheritance, and deinitialization.", "Choose semantics based on behavior, not perceived performance."], practicalUse: "Value semantics make state predictable; reference semantics suit shared services and identity-based objects.")
    static let protocols = LessonDetails(overview: "A protocol defines a contract of properties and methods without choosing the concrete implementation. Conforming types promise to satisfy those requirements.", keyPoints: ["Structs, classes, and enums can conform.", "Extensions can provide default implementations.", "Protocol-based dependencies improve substitution and testing."], practicalUse: "Protocols commonly define services, repositories, delegates, and reusable component capabilities.")
    static let generics = LessonDetails(overview: "Generics use type placeholders to express algorithms that work with many types while preserving compile-time safety.", keyPoints: ["T represents a type chosen by the caller.", "Constraints restrict T to required capabilities.", "Array, Set, Dictionary, and Result are generic types."], practicalUse: "Generics power reusable containers, networking layers, persistence helpers, and SwiftUI itself.")
    static let enums = LessonDetails(overview: "Enums model a finite set of valid cases. Associated values let each case carry exactly the information that state requires.", keyPoints: ["switch provides exhaustive case handling.", "Associated values can differ for every case.", "Enums prevent contradictory combinations of flags."], practicalUse: "Use enums for loading state, navigation routes, errors, filters, and domain workflows.")
    static let errors = LessonDetails(overview: "Swift error handling separates successful values from failures. Throwing functions propagate errors, while Result stores success or failure as a value.", keyPoints: ["Mark failing functions with throws.", "Call them using try and handle failures with catch.", "Use Result when an outcome must be stored or passed."], practicalUse: "Error handling is essential for validation, networking, file access, decoding, and persistence.")
    static let closures = LessonDetails(overview: "Closures are self-contained blocks of behavior. They can capture surrounding values, and @escaping allows a closure to run after its receiving function returns.", keyPoints: ["Capture lists control how references are captured.", "Escaping closures are stored or executed later.", "Use [weak self] to avoid reference cycles when appropriate."], practicalUse: "Callbacks, animations, sorting, event handlers, and asynchronous APIs rely heavily on closures.")
    static let arc = LessonDetails(overview: "Automatic Reference Counting tracks strong references to class instances and deallocates an instance when its strong-reference count reaches zero.", keyPoints: ["Strong is the default ownership relationship.", "weak does not retain and must be optional.", "unowned does not retain but assumes the object still exists."], practicalUse: "Correct ownership prevents memory leaks in delegates, parent-child relationships, callbacks, and long-running services.")
    static let concurrency = LessonDetails(overview: "Swift concurrency lets work suspend without blocking a thread. async marks asynchronous functions, await marks suspension points, and Task starts asynchronous work.", keyPoints: ["Suspension is not the same as blocking.", "UI state should be updated on the main actor.", "Structured tasks inherit cancellation and priority."], practicalUse: "Use concurrency for networking, database work, file loading, and other operations that should not freeze the UI.")
    static let swiftUI = LessonDetails(overview: "SwiftUI is declarative: a view describes what the interface should look like for the current state. When state changes, SwiftUI computes the necessary UI updates.", keyPoints: ["body is a description, not an imperative drawing routine.", "State is the source of truth.", "Views are lightweight value descriptions."], practicalUse: "Build interfaces by transforming app state into a hierarchy of views.")
    static let composition = LessonDetails(overview: "View composition builds complex screens from small views with clear inputs. Each component owns its appearance while its parent supplies data and actions.", keyPoints: ["Extract views with a single clear purpose.", "Pass data through immutable properties.", "Use closures or bindings for child-to-parent communication."], practicalUse: "Composition creates consistent design systems and keeps large screens readable, reusable, and testable.")
    static let swiftUIToolkit = LessonDetails(overview: "SwiftUI builds declarative interfaces by composing small views. Layout containers arrange content, modifiers configure it, collection views render data, and presentation APIs respond to state-driven navigation and actions.", keyPoints: ["HStack, VStack, ZStack, and Grid create layout; modifiers apply styling and behavior.", "List, ForEach, ScrollView, and lazy stacks efficiently present collections.", "Form, NavigationStack, TabView, sheets, full-screen covers, alerts, and dialogs structure complete app flows."], practicalUse: "These tools form the foundation of most production SwiftUI screens. Keep data and decisions in models or view models, then compose small views that declaratively render that state.")
    static let localState = LessonDetails(overview: "@State gives a view ownership of a small mutable value. SwiftUI stores that value outside the temporary view struct and refreshes dependent UI when it changes.", keyPoints: ["Declare @State as private when the view owns it.", "Use it for transient presentation state and simple controls.", "Do not use @State as a general persistence or dependency system."], practicalUse: "Use @State for toggles, selections, animation flags, draft input, and presentation booleans local to one screen.")
    static let binding = LessonDetails(overview: "@Binding provides read-and-write access to state owned elsewhere. A binding does not store the value; it connects a child control to its parent's source of truth.", keyPoints: ["The parent passes a binding using the $ prefix.", "The child can read and mutate the value.", "Ownership remains with the parent."], practicalUse: "Bindings power reusable controls, editors, toggles, and child views that must update parent-owned state.")
    static let observation = LessonDetails(overview: "The Observation framework tracks which @Observable properties a view reads. SwiftUI can then invalidate only the views depending on properties that actually changed.", keyPoints: ["Mark a model with @Observable.", "Own it with @State or inject it from a parent.", "Use @Bindable when a view needs bindings to observable properties."], practicalUse: "Observable models work well for feature state, editable forms, and presentation models with several related properties.")
    static let environment = LessonDetails(overview: "The environment propagates values and dependencies through a SwiftUI hierarchy without manually passing them through every intermediate view.", keyPoints: ["Ancestors provide a value with .environment.", "Descendants read it with @Environment.", "Keep dependencies explicit at feature boundaries."], practicalUse: "Use the environment for shared app settings, themes, locale, dismiss actions, and dependencies needed across a deep subtree.")
    static let mvvm = LessonDetails(overview: "MVVM separates a state-rendering View from a ViewModel that prepares presentation state and handles actions. Domain models remain independent of SwiftUI.", keyPoints: ["Views bind and render.", "ViewModels coordinate presentation logic.", "Models represent domain data and rules."], practicalUse: "MVVM is useful when a screen has meaningful logic, asynchronous work, validation, or behavior that deserves unit tests.")
    static let featureArchitecture = LessonDetails(overview: "Feature architecture groups code by user-facing capability instead of global technical type. Each feature can contain its own view, state, models, and tests.", keyPoints: ["Keep related changes close together.", "Extract Shared code only when genuinely reused.", "Define clear boundaries between features."], practicalUse: "Feature organization scales better as teams and codebases grow because ownership and dependencies are easier to understand.")
    static let dependencyInjection = LessonDetails(overview: "Dependency injection supplies collaborators from outside a type. The consumer depends on a capability rather than deciding which concrete implementation to construct.", keyPoints: ["Constructor injection makes requirements explicit.", "Protocols allow production and test implementations.", "Avoid hidden global dependencies."], practicalUse: "Inject API clients, clocks, analytics, storage, and repositories to make behavior configurable and tests deterministic.")
    static let repository = LessonDetails(overview: "A repository presents a domain-focused data interface while hiding whether data comes from memory, disk, a database, or the network.", keyPoints: ["Callers depend on data operations, not storage details.", "Implementations can add caching and synchronization.", "Tests can substitute an in-memory repository."], practicalUse: "Repositories are valuable when features must load and save domain data across replaceable or combined data sources.")
}
