import Foundation

struct LessonDetails {
    let overview: String
    let keyPoints: [String]
    let practicalUse: String
}

enum LessonDetailsCatalog {
    static let values = LessonDetails(overview: "Values give names to data. A constant declared with let cannot be reassigned, while a variable declared with var can change. Every value has a type, either written explicitly or inferred by Swift.", keyPoints: ["Prefer let until mutation is required.", "Common types include String, Int, Double, and Bool.", "Strong typing catches incompatible assignments at compile time."], practicalUse: "SwiftUI state, configuration, user input, and model properties all begin as constants or variables.")
    static let controlFlow = LessonDetails(overview: "Control flow decides which code runs and how often. Conditions use if, multi-case decisions use switch, and loops process sequences of values.", keyPoints: ["if handles Boolean conditions.", "switch should exhaustively cover every possible case.", "A for-in loop performs regular Swift work; SwiftUI ForEach creates views."], practicalUse: "Use control flow for validation, permissions, loading states, filtering, and preparing data for views.")
    static let functions = LessonDetails(overview: "Functions package related work behind a reusable name. Parameters supply input, return values provide output, and function types allow behavior to be passed around.", keyPoints: ["Parameter labels make calls readable.", "Use -> to declare a return type.", "Keep functions focused on one responsibility."], practicalUse: "Functions reduce repetition and make business logic independently testable.")
    static let optionals = LessonDetails(overview: "An optional represents either a wrapped value or nil. It forces missing data to be handled deliberately instead of allowing unsafe assumptions.", keyPoints: ["String? may contain a String or nil.", "Use if let for conditional work and guard let for early exits.", "Avoid force unwrapping with ! unless validity is guaranteed."], practicalUse: "Optionals appear in network responses, searches, user input, navigation selection, and failed conversions.")
    static let collections = LessonDetails(overview: "Collections store groups of values. Arrays preserve order, sets enforce uniqueness, and dictionaries associate unique keys with values.", keyPoints: ["Array access is index-based.", "Set membership checks are fast.", "Dictionary lookup returns an optional because a key may be absent."], practicalUse: "Most app screens render collections received from local storage or APIs.")
    static let semantics = LessonDetails(overview: "Structs are value types, so assigning them creates independent values. Classes are reference types, so multiple variables can point to the same instance and identity.", keyPoints: ["Swift models commonly use structs.", "Classes support identity, inheritance, and deinitialization.", "Choose semantics based on behavior, not perceived performance."], practicalUse: "Value semantics make state predictable; reference semantics suit shared services and identity-based objects.")
    static let protocols = LessonDetails(overview: "A protocol defines a contract of properties and methods without choosing the concrete implementation. Conforming types promise to satisfy those requirements.", keyPoints: ["Structs, classes, and enums can conform.", "Extensions can provide default implementations.", "Protocol-based dependencies improve substitution and testing."], practicalUse: "Protocols commonly define services, repositories, delegates, and reusable component capabilities.")
    static let generics = LessonDetails(overview: "Generics use type placeholders to express algorithms that work with many types while preserving compile-time safety.", keyPoints: ["T represents a type chosen by the caller.", "Constraints restrict T to required capabilities.", "Array, Set, Dictionary, and Result are generic types."], practicalUse: "Generics power reusable containers, networking layers, persistence helpers, and SwiftUI itself.")
    static let enums = LessonDetails(overview: "Enums model a finite set of valid cases. Associated values let each case carry exactly the information that state requires.", keyPoints: ["switch provides exhaustive case handling.", "Associated values can differ for every case.", "Enums prevent contradictory combinations of flags."], practicalUse: "Use enums for loading state, navigation routes, errors, filters, and domain workflows.")
    static let errors = LessonDetails(overview: "Swift error handling separates successful values from failures. Throwing functions propagate errors, while Result stores success or failure as a value.", keyPoints: ["Mark failing functions with throws.", "Call them using try and handle failures with catch.", "Use Result when an outcome must be stored or passed."], practicalUse: "Error handling is essential for validation, networking, file access, decoding, and persistence.")
    static let closures = LessonDetails(overview: "Closures are self-contained blocks of behavior. They can capture surrounding values, and @escaping allows a closure to run after its receiving function returns.", keyPoints: ["Capture lists control how references are captured.", "Escaping closures are stored or executed later.", "Use [weak self] to avoid reference cycles when appropriate."], practicalUse: "Callbacks, animations, sorting, event handlers, and asynchronous APIs rely heavily on closures.")
    static let arc = LessonDetails(overview: "Automatic Reference Counting tracks strong references to class instances and deallocates an instance when its strong-reference count reaches zero.", keyPoints: ["Strong is the default ownership relationship.", "weak does not retain and must be optional.", "unowned does not retain but assumes the object still exists."], practicalUse: "Correct ownership prevents memory leaks in delegates, parent-child relationships, callbacks, and long-running services.")
    static let concurrency = LessonDetails(overview: "Swift concurrency lets work suspend without blocking a thread. async marks asynchronous functions, await marks suspension points, and Task starts asynchronous work.", keyPoints: ["Suspension is not the same as blocking.", "UI state should be updated on the main actor.", "Structured tasks inherit cancellation and priority."], practicalUse: "Use concurrency for networking, database work, file loading, and other operations that should not freeze the UI.")
    static let swiftUI = LessonDetails(overview: "SwiftUI is declarative: a view describes what the interface should look like for the current state. When state changes, SwiftUI computes the necessary UI updates.", keyPoints: ["body is a description, not an imperative drawing routine.", "State is the source of truth.", "Views are lightweight value descriptions."], practicalUse: "Build interfaces by transforming app state into a hierarchy of views.")
    static let composition = LessonDetails(overview: "View composition builds complex screens from small views with clear inputs. Each component owns its appearance while its parent supplies data and actions.", keyPoints: ["Extract views with a single clear purpose.", "Pass data through immutable properties.", "Use closures or bindings for child-to-parent communication."], practicalUse: "Composition creates consistent design systems and keeps large screens readable, reusable, and testable.")
    static let swiftUIToolkit = LessonDetails(overview: "SwiftUI builds declarative interfaces by composing small views. Layout containers arrange content, modifiers configure it, collection views render data, and presentation APIs respond to state-driven navigation and actions.", keyPoints: ["HStack, VStack, ZStack, and Grid create layout; modifiers apply styling and behavior.", "List, ForEach, ScrollView, and lazy stacks efficiently present collections.", "Form, NavigationStack, TabView, sheets, full-screen covers, alerts, and dialogs structure complete app flows."], practicalUse: "These tools form the foundation of most production SwiftUI screens. Keep data and decisions in models or view models, then compose small views that declaratively render that state.")
    static let localState = LessonDetails(overview: "@State gives a view ownership of a small mutable value. SwiftUI stores that value outside the temporary view struct and refreshes dependent UI when it changes.", keyPoints: ["Declare @State as private when the view owns it.", "Use it for transient presentation state and simple controls.", "Do not use @State as a general persistence or dependency system."], practicalUse: "Use @State for toggles, selections, animation flags, draft input, and presentation booleans local to one screen.")
    static let binding = LessonDetails(overview: "@Binding provides read-and-write access to state owned elsewhere. A binding does not store the value; it connects a child control to its parent's source of truth.", keyPoints: ["The parent passes a binding using the $ prefix.", "The child can read and mutate the value.", "Ownership remains with the parent."], practicalUse: "Bindings power reusable controls, editors, toggles, and child views that must update parent-owned state.")
    static let observation = LessonDetails(overview: "The Observation framework tracks which @Observable properties a view reads. SwiftUI can then invalidate only the views depending on properties that actually changed.", keyPoints: ["Mark a model with @Observable.", "Own it with @State or inject it from a parent.", "Use @Bindable when a view needs bindings to observable properties."], practicalUse: "Observable models work well for feature state, editable forms, and presentation models with several related properties.")
    static let environment = LessonDetails(overview: "The environment propagates values and dependencies through a SwiftUI hierarchy without manually passing them through every intermediate view.", keyPoints: ["Ancestors provide a value with .environment.", "Descendants read it with @Environment.", "Keep dependencies explicit at feature boundaries."], practicalUse: "Use the environment for shared app settings, themes, locale, dismiss actions, and dependencies needed across a deep subtree.")
    static let mvvm = LessonDetails(overview: "MVVM separates a state-rendering View from a ViewModel that prepares presentation state and handles actions. Domain models remain independent of SwiftUI.", keyPoints: ["Views bind and render.", "ViewModels coordinate presentation logic.", "Models represent domain data and rules."], practicalUse: "MVVM is useful when a screen has meaningful logic, asynchronous work, validation, or behavior that deserves unit tests.")
    static let featureArchitecture = LessonDetails(overview: "Feature architecture groups code by user-facing capability instead of global technical type. Each feature can contain its own view, state, models, and tests.", keyPoints: ["Keep related changes close together.", "Extract Shared code only when genuinely reused.", "Define clear boundaries between features."], practicalUse: "Feature organization scales better as teams and codebases grow because ownership and dependencies are easier to understand.")
    static let dependencyInjection = LessonDetails(overview: "Dependency injection supplies collaborators from outside a type. The consumer depends on a capability rather than deciding which concrete implementation to construct.", keyPoints: ["Constructor injection makes requirements explicit.", "Protocols allow production and test implementations.", "Avoid hidden global dependencies."], practicalUse: "Inject API clients, clocks, analytics, storage, and repositories to make behavior configurable and tests deterministic.")
    static let repository = LessonDetails(overview: "A repository presents a domain-focused data interface while hiding whether data comes from memory, disk, a database, or the network.", keyPoints: ["Callers depend on data operations, not storage details.", "Implementations can add caching and synchronization.", "Tests can substitute an in-memory repository."], practicalUse: "Repositories are valuable when features must load and save domain data across replaceable or combined data sources.")
    static let networking = LessonDetails(overview: "A networking layer builds HTTP requests, uses URLSession to transfer bytes, validates server responses, and converts JSON into typed Codable models. REST defines resource-oriented HTTP conventions, while WebSockets keep a bidirectional connection open for real-time messages.", keyPoints: ["Validate HTTP status codes before decoding response data.", "Use Codable with JSONEncoder and JSONDecoder for typed serialization.", "Use upload/download tasks for files and URLSessionWebSocketTask for real-time connections."], practicalUse: "Production apps normally place URLSession behind an injected client or repository, handle authentication and cancellation, and model loading, success, and failure explicitly.")
    static let swiftData = LessonDetails(overview: "SwiftData is Apple's modern persistence framework. @Model defines persisted types, ModelContext performs mutations, and @Query keeps SwiftUI synchronized with stored data.", keyPoints: ["Use @Model for persistent reference types.", "Insert and delete through ModelContext.", "Use @Query for reactive, sortable fetches."], practicalUse: "SwiftData is a strong default for new Apple-platform apps that need structured local persistence and do not require an existing Core Data stack.")
    static let coreData = LessonDetails(overview: "Core Data is a mature object-graph and persistence framework built around managed object models, persistent stores, contexts, and fetch requests.", keyPoints: ["NSPersistentContainer coordinates the stack.", "NSManagedObjectContext tracks changes.", "Fetch requests query managed objects."], practicalUse: "Core Data remains important for established apps, complex migrations, mature tooling, and projects that already depend on managed object models.")
    static let sqlite = LessonDetails(overview: "SQLite is an embedded relational database. Apps define tables and use SQL statements to insert, select, update, and delete rows.", keyPoints: ["Schemas define tables, columns, and constraints.", "Prepared statements safely bind input values.", "Transactions group changes atomically."], practicalUse: "Use SQLite directly when precise SQL control is required, or through a higher-level library when raw C APIs would add unnecessary complexity.")
    static let userDefaults = LessonDetails(overview: "UserDefaults stores small property-list values as application preferences. SwiftUI's @AppStorage creates a reactive connection to a defaults key.", keyPoints: ["Use it for small preferences, not large datasets.", "Provide stable keys and sensible defaults.", "Never treat UserDefaults as secure storage."], practicalUse: "Good uses include onboarding flags, selected appearance, sort order, and lightweight user preferences.")
    static let keychain = LessonDetails(overview: "Keychain Services stores small secrets in an encrypted system-managed database. Items are identified by attributes such as service and account.", keyPoints: ["Use SecItemAdd, SecItemCopyMatching, and SecItemDelete.", "Select an accessibility policy appropriate to the secret.", "Do not store authentication tokens in UserDefaults."], practicalUse: "Use Keychain for access tokens, refresh tokens, passwords, cryptographic keys, and other credentials.")
    static let fileManager = LessonDetails(overview: "FileManager works with files and directories inside the app sandbox. Codable data, media, exports, and caches can be written to purpose-specific locations.", keyPoints: ["Documents/Application Support hold durable user data.", "Caches contains replaceable data.", "Temporary files may be removed by the system."], practicalUse: "Use files for documents, images, downloaded media, encoded models, logs, caches, imports, and exports.")
    static let asyncImage = LessonDetails(overview: "AsyncImage loads a remote URL and renders its empty, success, or failure phase. It is convenient for basic images but does not provide a full production cache policy.", keyPoints: ["Render every AsyncImagePhase.", "Reserve space to avoid layout shifts.", "Use a dedicated pipeline for advanced caching and transforms."], practicalUse: "Use AsyncImage for simple remote artwork where basic loading behavior is sufficient.")
    static let imagePipeline = LessonDetails(overview: "An image pipeline coordinates network download, response validation, off-main decoding, caching, cancellation, and reuse.", keyPoints: ["Cache decoded images with NSCache.", "Deduplicate requests and support cancellation.", "Downsample large images near their display size."], practicalUse: "Production feeds and grids benefit from a pipeline that avoids repeated downloads and expensive full-resolution decoding.")
    static let photos = LessonDetails(overview: "PhotosPicker provides privacy-focused access to user-selected library assets. Transferable loads only the selected content into the app.", keyPoints: ["Prefer the system picker over broad library access.", "Load selected data asynchronously.", "Handle cancellation and unsupported formats."], practicalUse: "Use PhotosPicker for avatars, attachments, image editors, and media uploads.")
    static let camera = LessonDetails(overview: "AVFoundation camera capture uses authorization, an AVCaptureSession, device inputs, and photo or video outputs. Session configuration should not block the main thread.", keyPoints: ["Request camera access before starting capture.", "Configure inputs and outputs between beginConfiguration and commitConfiguration.", "Stop sessions when capture UI is no longer active."], practicalUse: "Use direct AVFoundation control for scanners, custom camera interfaces, and specialized capture workflows.")
    static let videoPlayer = LessonDetails(overview: "AVPlayer manages time-based playback from local or remote media. SwiftUI's VideoPlayer supplies standard controls around an AVPlayer instance.", keyPoints: ["Keep the player alive for the view lifetime.", "Observe lifecycle and playback status.", "Pause playback when leaving the screen."], practicalUse: "Use AVPlayer for lessons, streaming clips, previews, and custom playback experiences.")
    static let videoRecording = LessonDetails(overview: "Video recording combines camera and microphone inputs with AVCaptureMovieFileOutput or a custom sample-buffer pipeline.", keyPoints: ["Camera and microphone permissions are separate.", "Configure the session before recording.", "Process output URLs and errors in the recording delegate."], practicalUse: "Use AVFoundation recording for camera apps, user-generated content, and workflows needing capture control or editing.")
    static let audioPlayer = LessonDetails(overview: "AVAudioPlayer plays local or downloaded audio files and exposes duration, current time, looping, volume, and delegate callbacks.", keyPoints: ["Retain the player while audio is playing.", "Configure an AVAudioSession for the app's audio behavior.", "Prepare before latency-sensitive playback."], practicalUse: "Use AVAudioPlayer for sound effects, voice notes, and straightforward file playback.")
    static let audioRecorder = LessonDetails(overview: "AVAudioRecorder writes microphone input to a file using a chosen format and quality configuration.", keyPoints: ["Request microphone permission.", "Choose an audio-session category that supports recording.", "Stop and release recording resources responsibly."], practicalUse: "Use AVAudioRecorder for voice notes, audio attachments, and simple microphone recording.")
    static let audioEngine = LessonDetails(overview: "AVAudioEngine connects audio nodes into a real-time processing graph. Input taps expose audio buffers for metering, analysis, effects, or transcription.", keyPoints: ["Install taps with a suitable buffer size and format.", "Keep real-time callbacks lightweight.", "Remove taps and stop the engine during cleanup."], practicalUse: "Use AVAudioEngine for waveform meters, effects, speech pipelines, mixing, and advanced audio processing.")
}
